name: "Check for Python file changes"
description: "Checks if there are any Python (.py) files changed in the PR."
inputs:
  base_branch:
    description: "The branch to compare against (default is the PR base branch)"
    required: false
    default: ${{ github.base_ref }}

outputs:
  value:
    description: "Returns 'true' if .py files are changed, 'false' otherwise."
    value: ""

runs:
  using: "composite"
  steps:
    - name: Fetch the compare branch
      shell: bash
      run: |
        git fetch origin ${{ inputs.base_branch }}

    - name: Check for .py file changes
      shell: bash
      id: check_files
      run: |
        if git diff --name-only origin/${{ inputs.base_branch }} | grep -q '\.py$'; then
          echo "value=true" >> $GITHUB_ENV
        else
          echo "value=false" >> $GITHUB_ENV
        fi
        echo $GITHUB_ENV