name: "pip-install"
description: "Install Python dependencies with pip, using cache if available"

inputs:
  packages:
    description: "Python packages to install (e.g., 'black requests')"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/') }}-${{ inputs.packages }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: pip install --cache-dir ~/.cache/pip ${{ inputs.packages }}