name: "pip-install"
description: "Install Python dependencies with pip, using cache if available"

inputs:
  packages:
    description: "Python packages to install (e.g., 'black requests')"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/') }}-${{ inputs.packages }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      shell: bash
      run: pip install --cache-dir ~/.cache/pip ${{ inputs.packages }}