name: Check python format with black

on:
  push:
  workflow_dispatch:

jobs:
  job_read_config:
    runs-on: [ubuntu-latest]
    outputs:
      config: ${{ steps.read_data_from_config.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Read datas from the config
        id: read_data_from_config
        uses: ./.github/actions/read-yaml

  job_check_format:
    needs: job_read_config  # job_a의 실행 결과에 의존
    runs-on: ${{ fromJson(needs.job_read_config.outputs.config)['runs-on'] }}
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.job_read_config.outputs.config)['python-targets'] }}  # 테스트할 Python 버전 목록
    steps:
      - uses: ./.github/actions/check-format
        with:
          path: .
