name: Trigger on Pull Request to Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  job_read_config:
    runs-on: [ubuntu-latest]
    outputs:
      config: ${{ steps.read_data_from_config.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Read datas from the config
        id: read_data_from_config
        uses: ./.github/actions/read-yaml
      - name: Display the config
        shell: bash
        run: echo ${{ steps.read_data_from_config.outputs.value }}

  job_check_py_changes:
    runs-on: ubuntu-latest
    outputs:
      is_changed: ${{ steps.check_py_changes.outputs.is_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check job changes
        uses: ./.github/actions/check-py-changes
        id: check_py_changes
      - name: Check
        shell: bash
        run: |
          echo steps.check_py_changes.outputs.is_changed
          echo ${{ steps.check_py_changes.outputs.is_changed }}

  job_script_validation:
    needs: [job_read_config, job_check_py_changes]
    if: needs.job_check_py_changes.outputs.is_changed  == 'true'
    runs-on: ${{ fromJson(needs.job_read_config.outputs.config)['workflows']['runs-on'] }}
    strategy:
      matrix:
        container: ${{ fromJson(needs.job_read_config.outputs.config)['workflows']['docker-targets'] }}  # 테스트할 Python 버전 목록
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-pip
        with:
          packages: .
      - uses: ./.github/actions/check-format
        with:
          path: .
      - uses: ./.github/actions/pytest
        with:
          path: .