name: Check python format with black

on:
  push:
  workflow_dispatch:

jobs:
  job_read_config:
    runs-on: [ubuntu-latest]
    outputs:
      config: ${{ steps.read_data_from_config.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Read datas from the config
        id: read_data_from_config
        uses: ./.github/actions/read-yaml
      - name: Display the config
        shell: bash
        run: echo ${{ steps.read_data_from_config.outputs.value }}
  job_temp_test:
    needs: job_read_config
    runs-on: ubuntu-latest
    steps:
      - name: e
        run: |
          echo ${{ needs.job_read_config.outputs.config }}
          echo ${{ fromJson(needs.job_read_config.outputs.config) }}
          echo ${{ fromJson(needs.job_read_config.outputs.config)['runs-on'] }}
          echo ${{ fromJson(needs.job_read_config.outputs.config)['python-targets'] }}

  job_check_format:
    needs: job_read_config
    runs-on: ${{ fromJson(needs.job_read_config.outputs.config)['runs-on'] }}
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.job_read_config.outputs.config)['python-targets'] }}  # 테스트할 Python 버전 목록
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/check-format
        with:
          path: .
